### ISSUE TITLE
[Bug]: Cant install

### ISSUE THREAD

**Issue by projct1** [saas-laravel/laravel-enums-to-json#6]
### What happened?

![image](https://github.com/saas-laravel/laravel-enums-to-json/assets/9752959/96955407-e4a3-45a8-bd57-22213761a72d)

### How to reproduce the bug

Try to install.

### Package Version

Main

### PHP Version

8.3

### Laravel Version

10.44

**Comment by przemyslaw-przylucki** [comment]
Should be resolved now =)
